### ISSUE TITLE
[IDEA] Bot owner bypasses all permissions

### ISSUE THREAD

**Issue by Mirrage0** [200percentmicky/chadmusic#17]
Contrary to the title, it would be majorly handy if the bot owner can bypass the permissions check. At the moment I am having a go at this myself and if I do this successfully ill make a pull req.
Do you have any tips on where I can look exactly and what to do etc?

Cheers

**Comment by 200percentmicky** [comment]
If you're talking about DJ permissions, the check for that was actually implemented a while ago [here](https://github.com/200percentmicky/chadmusic/blob/e9585f397ed49261353b95872c7ef829e7a5a3f9/src/modules/ChadUtils.js#L56), but only the playlists commands use that check. To be honest, I find it funny that I haven't even fully incorporated it throughout the whole bot yet. lol

As for the pull request, thank you for your interest in wanting to contribute, but I do have a couple of points regarding it:
- You don't have to go out of your way to create the PR for this issue right now as this is something that I can easily implement on my end.
- Considering that this project is currently just a hobby and is developed on my free time, I'm a bit iffy on accepting pull requests at this time, but there is no problem if you ever wanted to open one anytime.

**Comment by 200percentmicky** [comment]
The checks have now been implemented fully in 816e2cbc173f58875a458e51f7b92579721dd020.

I did make the feature something you would need to opt into instead of having it enabled automatically in 2d66e1697e5ffb7c76d266248a40009ff11c94c0. I would assume that not every server admin would want for the bot owner to bypass DJ permissions by default unless stated otherwise, but then again most probably wouldn't care either way. Right now, you can enable it using eval, but commands to manage it will be added later.
